/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Background: typeof import('./../components/Background.vue')['default']
    BackTop: typeof import('./../components/BackTop.vue')['default']
    BaseECharts: typeof import('./../components/BaseECharts.vue')['default']
    Cover: typeof import('./../components/login/Cover.vue')['default']
    LoginFrom: typeof import('./../components/login/LoginFrom.vue')['default']
    RegFrom: typeof import('./../components/login/RegFrom.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
